services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: rebuild
          path: ./app.js
          target: /app/app.js
        - action: rebuild
          path: ./package.json
          target: /app/package.json
        - action: rebuild
          path: ./package-lock.json
          target: /app/package-lock.json