replicaCount: 1

image:
  pullSecrets: []
  # - name: myRegistryKeySecret
  repository: ghcr.io/martysweet/headless-render-api
  pullPolicy: IfNotPresent
  tag: "latest"

valkey:
  enabled: true
  image:
    repository: valkey/valkey
    pullPolicy: IfNotPresent
    tag: "8.1.3-alpine"
  resources:
    limits:
      memory: "256Mi"
    requests:
      memory: "256Mi"
      cpu: "100m"

nodeSelector: {}
affinity: {}
tolerations: {}

service:
  type: ClusterIP
  port: 3000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60

ingress:
  enabled: false
  className: "something"
  hosts:
    - host: yourhost
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - yourhost

resources:
  limits:
      memory: 256Mi
  requests:
      cpu: 500m
      memory: 256Mi