name: Build and Push Docker Image

on:
  push:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tags
        id: vars
        run: |
          SHA_TAG=$(echo $GITHUB_SHA | cut -c1-7)
          BRANCH_TAG=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          echo "sha_tag=$SHA_TAG" >> $GITHUB_OUTPUT
          echo "branch_tag=$BRANCH_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_tag }}
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.branch_tag }}
            ${{ github.ref_name == 'main' && format('ghcr.io/{0}:latest', github.repository) || '' }}
